version: '3'

services:
  kong:
    image: kong/kong-gateway:2.8
    #build: .
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_LOG_LEVEL=info
      - KONG_PLUGINS=bundled,helloworld
      - KONG_NGINX_DAEMON=off
      - KONG_LUA_PACKAGE_PATH=/custom-plugins/?.lua;/custom-plugins/?/init.lua;;
      - KONG_ADMIN_ACCESS_LOG=/proc/self/fd/1
      - KONG_ADMIN_ERROR_LOG=/proc/self/fd/2
      - KONG_PROXY_ACCESS_LOG=/proc/self/fd/1
      - KONG_PROXY_ERROR_LOG=/proc/self/fd/2
      - KONG_NGINX_WORKER_PROCESSES=1
      - SET_CONTAINER_TIMEZONE_ON_START=true
      - CONTAINER_TIMEZONE=CET
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    volumes:
      - ./src/kong:/custom-plugins/kong
    command: bash -c "kong migrations bootstrap && ./docker-entrypoint-kong.sh kong docker-start"

  kong-database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    #volume